# SPDX-License-Identifier: Marvell-MIT
# Copyright (c) 2025 Marvell.

sources = files(
		'rdma_config.c',
		'rdma_eth_init.c',
		'rdma_eth_rx.c',
		'rdma_eth_tx.c',
		'rdma_graph_init.c',
		'rdma_main.c',
		'rdma_node_ctrl.c',
		'rdma_process.c',
		'rdma_dma_init.c',
		'rdma_pem_init.c',
		'rdma_pts_enq.c',
		'rdma_pts_deq.c',
    'rdma_rss.c',
)

deps += ['common', 'pem', 'rdma', 'pts_rdma']
