# SPDX-License-Identifier: Marvell-MIT
# Copyright (c) 2025 Marvell.

################################################################################
# liboqs
################################################################################

LIBOQS_VERSION = 0.13.0-rc1
LIBOQS_SITE = https://github.com/open-quantum-safe/liboqs.git
LIBOQS_SITE_METHOD = git
LIBOQS_LICENSE = MIT
LIBOQS_LICENSE_FILES = LICENSE.txt

BR_NO_CHECK_HASH_FOR += $(LIBOQS_SOURCE)
LIBOQS_INSTALL_STAGING = YES

LIBOQS_DEPENDENCIES = \
	host-pkgconf \
	host-cmake

# Use CMake build system
LIBOQS_CONF_OPTS = \
	-DBUILD_SHARED_LIBS=ON \
	-DOQS_BUILD_ONLY_LIB=ON \
	-DOQS_DIST_BUILD=ON

ifeq ($(BR2_PACKAGE_LIBOQS_ENABLE_OPENSSL),y)
LIBOQS_DEPENDENCIES += openssl
LIBOQS_CONF_OPTS += -DOQS_USE_OPENSSL=ON
else
LIBOQS_CONF_OPTS += -DOQS_USE_OPENSSL=OFF
endif

ifeq ($(BR2_PACKAGE_LIBOQS_ENABLE_AES_NI),y)
LIBOQS_CONF_OPTS += -DOQS_USE_AES_INSTRUCTIONS=ON
else
LIBOQS_CONF_OPTS += -DOQS_USE_AES_INSTRUCTIONS=OFF
endif

ifeq ($(BR2_PACKAGE_LIBOQS_ENABLE_AVX),y)
LIBOQS_CONF_OPTS += -DOQS_USE_AVX_INSTRUCTIONS=ON
else
LIBOQS_CONF_OPTS += -DOQS_USE_AVX_INSTRUCTIONS=OFF
endif

ifeq ($(BR2_PACKAGE_LIBOQS_ENABLE_AVX2),y)
LIBOQS_CONF_OPTS += -DOQS_USE_AVX2_INSTRUCTIONS=ON
else
LIBOQS_CONF_OPTS += -DOQS_USE_AVX2_INSTRUCTIONS=OFF
endif

ifeq ($(BR2_PACKAGE_LIBOQS_ENABLE_NEON),y)
LIBOQS_CONF_OPTS += -DOQS_USE_ARM_NEON_INSTRUCTIONS=ON
else
LIBOQS_CONF_OPTS += -DOQS_USE_ARM_NEON_INSTRUCTIONS=OFF
endif

ifeq ($(BR2_PACKAGE_LIBOQS_BUILD_TESTS),y)
LIBOQS_CONF_OPTS += -DOQS_BUILD_TESTS=ON
else
LIBOQS_CONF_OPTS += -DOQS_BUILD_TESTS=OFF
endif

ifeq ($(BR2_PACKAGE_LIBOQS_BUILD_EXAMPLES),y)
LIBOQS_CONF_OPTS += -DOQS_BUILD_EXAMPLES=ON
else
LIBOQS_CONF_OPTS += -DOQS_BUILD_EXAMPLES=OFF
endif

ifeq ($(BR2_PACKAGE_LIBOQS_ENABLE_KEM_CLASSIC_MCELIECE),y)
LIBOQS_CONF_OPTS += -DOQS_ENABLE_KEM_classic_mceliece=ON
else
LIBOQS_CONF_OPTS += -DOQS_ENABLE_KEM_classic_mceliece=OFF
endif

ifeq ($(BR2_PACKAGE_LIBOQS_ENABLE_KEM_KYBER),y)
LIBOQS_CONF_OPTS += -DOQS_ENABLE_KEM_kyber=ON
else
LIBOQS_CONF_OPTS += -DOQS_ENABLE_KEM_kyber=OFF
endif

ifeq ($(BR2_PACKAGE_LIBOQS_ENABLE_KEM_FRODOKEM),y)
LIBOQS_CONF_OPTS += -DOQS_ENABLE_KEM_frodokem=ON
else
LIBOQS_CONF_OPTS += -DOQS_ENABLE_KEM_frodokem=OFF
endif

ifeq ($(BR2_PACKAGE_LIBOQS_ENABLE_SIG_DILITHIUM),y)
LIBOQS_CONF_OPTS += -DOQS_ENABLE_SIG_dilithium=ON
else
LIBOQS_CONF_OPTS += -DOQS_ENABLE_SIG_dilithium=OFF
endif

ifeq ($(BR2_PACKAGE_LIBOQS_ENABLE_SIG_FALCON),y)
LIBOQS_CONF_OPTS += -DOQS_ENABLE_SIG_falcon=ON
else
LIBOQS_CONF_OPTS += -DOQS_ENABLE_SIG_falcon=OFF
endif

ifeq ($(BR2_PACKAGE_LIBOQS_ENABLE_SIG_SPHINCS),y)
LIBOQS_CONF_OPTS += -DOQS_ENABLE_SIG_sphincs=ON
else
LIBOQS_CONF_OPTS += -DOQS_ENABLE_SIG_sphincs=OFF
endif

# Platform-specific optimizations
ifneq ($(BR2_MARVELL_MESON_PROPERTIES_PLATFORM),)
# For Marvell platforms, enable ARM optimizations
ifeq ($(BR2_aarch64),y)
LIBOQS_CONF_OPTS += -DOQS_USE_ARM_NEON_INSTRUCTIONS=ON
endif
endif

$(eval $(cmake-package))
