/* SPDX-License-Identifier: Marvell-MIT
 * Copyright (c) 2025 Marvell.
 */

#ifndef __RDMA_OPCODE_H_
#define __RDMA_OPCODE_H_

#include "rte_bitops.h"

enum rdma_hdr_type {
	RDMA_LRH,
	RDMA_GRH,
	RDMA_BTH,
	RDMA_RETH,
	RDMA_AETH,
	RDMA_ATMETH,
	RDMA_ATMACK,
	RDMA_IETH,
	RDMA_RDETH,
	RDMA_DETH,
	RDMA_IMMDT,
	RDMA_PAYLOAD,
	NUM_HDR_TYPES
};

enum rdma_hdr_mask {
	RDMA_LRH_MASK = RTE_BIT32(RDMA_LRH),
	RDMA_GRH_MASK = RTE_BIT32(RDMA_GRH),
	RDMA_BTH_MASK = RTE_BIT32(RDMA_BTH),
	RDMA_IMMDT_MASK = RTE_BIT32(RDMA_IMMDT),
	RDMA_RETH_MASK = RTE_BIT32(RDMA_RETH),
	RDMA_AETH_MASK = RTE_BIT32(RDMA_AETH),
	RDMA_ATMETH_MASK = RTE_BIT32(RDMA_ATMETH),
	RDMA_ATMACK_MASK = RTE_BIT32(RDMA_ATMACK),
	RDMA_IETH_MASK = RTE_BIT32(RDMA_IETH),
	RDMA_RDETH_MASK = RTE_BIT32(RDMA_RDETH),
	RDMA_DETH_MASK = RTE_BIT32(RDMA_DETH),
	RDMA_PAYLOAD_MASK = RTE_BIT32(RDMA_PAYLOAD),

	RDMA_REQ_MASK = RTE_BIT32(NUM_HDR_TYPES + 0),
	RDMA_ACK_MASK = RTE_BIT32(NUM_HDR_TYPES + 1),
	RDMA_SEND_MASK = RTE_BIT32(NUM_HDR_TYPES + 2),
	RDMA_WRITE_MASK = RTE_BIT32(NUM_HDR_TYPES + 3),
	RDMA_READ_MASK = RTE_BIT32(NUM_HDR_TYPES + 4),
	RDMA_ATOMIC_MASK = RTE_BIT32(NUM_HDR_TYPES + 5),

	RDMA_RWR_MASK = RTE_BIT32(NUM_HDR_TYPES + 6),
	RDMA_COMP_MASK = RTE_BIT32(NUM_HDR_TYPES + 7),

	RDMA_START_MASK = RTE_BIT32(NUM_HDR_TYPES + 8),
	RDMA_MIDDLE_MASK = RTE_BIT32(NUM_HDR_TYPES + 9),
	RDMA_END_MASK = RTE_BIT32(NUM_HDR_TYPES + 10),

	RDMA_LOOPBACK_MASK = RTE_BIT32(NUM_HDR_TYPES + 12),

	RDMA_READ_OR_ATOMIC_MASK = (RDMA_READ_MASK | RDMA_ATOMIC_MASK),
	RDMA_WRITE_OR_SEND_MASK = (RDMA_WRITE_MASK | RDMA_SEND_MASK),
	RDMA_READ_OR_WRITE_MASK = (RDMA_READ_MASK | RDMA_WRITE_MASK),
};

#define OPCODE_NONE     (-1)
#define RDMA_NUM_OPCODE 256

#define RDMA_OPCODE(transport, op)                                                                 \
	RDMA_OPCODE_##transport##_##op = RDMA_OPCODE_##transport + RDMA_OPCODE_##op

enum {
	/* transport types -- just used to define real constants */
	RDMA_OPCODE_RC = 0x00,
	RDMA_OPCODE_UC = 0x20,
	RDMA_OPCODE_RD = 0x40,
	RDMA_OPCODE_UD = 0x60,
	/* per RDMTA 1.3 vol 1 Table 38, A10.3.2 */
	RDMA_OPCODE_CNP = 0x80,
	/* Manufacturer specific */
	RDMA_OPCODE_MSP = 0xe0,

	/* operations -- just used to define real constants */
	RDMA_OPCODE_SEND_FIRST = 0x00,
	RDMA_OPCODE_SEND_MIDDLE = 0x01,
	RDMA_OPCODE_SEND_LAST = 0x02,
	RDMA_OPCODE_SEND_LAST_WITH_IMMEDIATE = 0x03,
	RDMA_OPCODE_SEND_ONLY = 0x04,
	RDMA_OPCODE_SEND_ONLY_WITH_IMMEDIATE = 0x05,
	RDMA_OPCODE_RDMA_WRITE_FIRST = 0x06,
	RDMA_OPCODE_RDMA_WRITE_MIDDLE = 0x07,
	RDMA_OPCODE_RDMA_WRITE_LAST = 0x08,
	RDMA_OPCODE_RDMA_WRITE_LAST_WITH_IMMEDIATE = 0x09,
	RDMA_OPCODE_RDMA_WRITE_ONLY = 0x0a,
	RDMA_OPCODE_RDMA_WRITE_ONLY_WITH_IMMEDIATE = 0x0b,
	RDMA_OPCODE_RDMA_READ_REQUEST = 0x0c,
	RDMA_OPCODE_RDMA_READ_RESPONSE_FIRST = 0x0d,
	RDMA_OPCODE_RDMA_READ_RESPONSE_MIDDLE = 0x0e,
	RDMA_OPCODE_RDMA_READ_RESPONSE_LAST = 0x0f,
	RDMA_OPCODE_RDMA_READ_RESPONSE_ONLY = 0x10,
	RDMA_OPCODE_ACKNOWLEDGE = 0x11,
	RDMA_OPCODE_ATOMIC_ACKNOWLEDGE = 0x12,
	RDMA_OPCODE_COMPARE_SWAP = 0x13,
	RDMA_OPCODE_FETCH_ADD = 0x14,
	/* opcode 0x15 is reserved */
	RDMA_OPCODE_SEND_LAST_WITH_INVALIDATE = 0x16,
	RDMA_OPCODE_SEND_ONLY_WITH_INVALIDATE = 0x17,

	/* real constants follow -- see comment about above RDMA_OPCODE()
	   macro for more details */

	/* RC */
	RDMA_OPCODE(RC, SEND_FIRST),
	RDMA_OPCODE(RC, SEND_MIDDLE),
	RDMA_OPCODE(RC, SEND_LAST),
	RDMA_OPCODE(RC, SEND_LAST_WITH_IMMEDIATE),
	RDMA_OPCODE(RC, SEND_ONLY),
	RDMA_OPCODE(RC, SEND_ONLY_WITH_IMMEDIATE),
	RDMA_OPCODE(RC, RDMA_WRITE_FIRST),
	RDMA_OPCODE(RC, RDMA_WRITE_MIDDLE),
	RDMA_OPCODE(RC, RDMA_WRITE_LAST),
	RDMA_OPCODE(RC, RDMA_WRITE_LAST_WITH_IMMEDIATE),
	RDMA_OPCODE(RC, RDMA_WRITE_ONLY),
	RDMA_OPCODE(RC, RDMA_WRITE_ONLY_WITH_IMMEDIATE),
	RDMA_OPCODE(RC, RDMA_READ_REQUEST),
	RDMA_OPCODE(RC, RDMA_READ_RESPONSE_FIRST),
	RDMA_OPCODE(RC, RDMA_READ_RESPONSE_MIDDLE),
	RDMA_OPCODE(RC, RDMA_READ_RESPONSE_LAST),
	RDMA_OPCODE(RC, RDMA_READ_RESPONSE_ONLY),
	RDMA_OPCODE(RC, ACKNOWLEDGE),
	RDMA_OPCODE(RC, ATOMIC_ACKNOWLEDGE),
	RDMA_OPCODE(RC, COMPARE_SWAP),
	RDMA_OPCODE(RC, FETCH_ADD),
	RDMA_OPCODE(RC, SEND_LAST_WITH_INVALIDATE),
	RDMA_OPCODE(RC, SEND_ONLY_WITH_INVALIDATE),

	/* UC */
	RDMA_OPCODE(UC, SEND_FIRST),
	RDMA_OPCODE(UC, SEND_MIDDLE),
	RDMA_OPCODE(UC, SEND_LAST),
	RDMA_OPCODE(UC, SEND_LAST_WITH_IMMEDIATE),
	RDMA_OPCODE(UC, SEND_ONLY),
	RDMA_OPCODE(UC, SEND_ONLY_WITH_IMMEDIATE),
	RDMA_OPCODE(UC, RDMA_WRITE_FIRST),
	RDMA_OPCODE(UC, RDMA_WRITE_MIDDLE),
	RDMA_OPCODE(UC, RDMA_WRITE_LAST),
	RDMA_OPCODE(UC, RDMA_WRITE_LAST_WITH_IMMEDIATE),
	RDMA_OPCODE(UC, RDMA_WRITE_ONLY),
	RDMA_OPCODE(UC, RDMA_WRITE_ONLY_WITH_IMMEDIATE),

	/* RD */
	RDMA_OPCODE(RD, SEND_FIRST),
	RDMA_OPCODE(RD, SEND_MIDDLE),
	RDMA_OPCODE(RD, SEND_LAST),
	RDMA_OPCODE(RD, SEND_LAST_WITH_IMMEDIATE),
	RDMA_OPCODE(RD, SEND_ONLY),
	RDMA_OPCODE(RD, SEND_ONLY_WITH_IMMEDIATE),
	RDMA_OPCODE(RD, RDMA_WRITE_FIRST),
	RDMA_OPCODE(RD, RDMA_WRITE_MIDDLE),
	RDMA_OPCODE(RD, RDMA_WRITE_LAST),
	RDMA_OPCODE(RD, RDMA_WRITE_LAST_WITH_IMMEDIATE),
	RDMA_OPCODE(RD, RDMA_WRITE_ONLY),
	RDMA_OPCODE(RD, RDMA_WRITE_ONLY_WITH_IMMEDIATE),
	RDMA_OPCODE(RD, RDMA_READ_REQUEST),
	RDMA_OPCODE(RD, RDMA_READ_RESPONSE_FIRST),
	RDMA_OPCODE(RD, RDMA_READ_RESPONSE_MIDDLE),
	RDMA_OPCODE(RD, RDMA_READ_RESPONSE_LAST),
	RDMA_OPCODE(RD, RDMA_READ_RESPONSE_ONLY),
	RDMA_OPCODE(RD, ACKNOWLEDGE),
	RDMA_OPCODE(RD, ATOMIC_ACKNOWLEDGE),
	RDMA_OPCODE(RD, COMPARE_SWAP),
	RDMA_OPCODE(RD, FETCH_ADD),

	/* UD */
	RDMA_OPCODE(UD, SEND_ONLY),
	RDMA_OPCODE(UD, SEND_ONLY_WITH_IMMEDIATE)
};

struct rdma_opcode_info {
	const char *name;
	enum rdma_hdr_mask mask;
	int length;
	int offset[NUM_HDR_TYPES];
};

enum rdma_wr_mask {
	WR_SEND_MASK = RTE_BIT32(2),
	WR_READ_MASK = RTE_BIT32(3),
	WR_WRITE_MASK = RTE_BIT32(4),
	WR_LOCAL_OP_MASK = RTE_BIT32(5),
	WR_FLUSH_MASK = RTE_BIT32(6),

	WR_READ_OR_WRITE_MASK = WR_READ_MASK | WR_WRITE_MASK,
	WR_WRITE_OR_SEND_MASK = WR_WRITE_MASK | WR_SEND_MASK,
};

/*TODO FIXME*/
#define RRDMA_QPT_MAX 12
struct rdma_wr_opcode_info {
	const char *name;
	enum rdma_wr_mask mask[RRDMA_QPT_MAX];
};

/*TODO FIXME*/
#define RRDMA_WR_REG_MR 17

extern struct rdma_wr_opcode_info rdma_wr_opcode_info[RRDMA_WR_REG_MR];
extern struct rdma_opcode_info rdma_opcode[RDMA_NUM_OPCODE];

enum RDMA_send_flags {
	RDMA_SEND_FENCE = 1,
	RDMA_SEND_SIGNALED = (1 << 1),
	RDMA_SEND_SOLICITED = (1 << 2),
	RDMA_SEND_INLINE = (1 << 3),
	RDMA_SEND_IP_CSUM = (1 << 4),
};

#endif /* __RDMA_OPCODE_H_ */
