/* SPDX-License-Identifier: Marvell-MIT
 * Copyright (c) 2025 Marvell.
 */

#include "rdma_opcode.h"
#include "rdma_hdr.h"
#include "rdma_priv.h"

struct rdma_opcode_info rdma_opcode[RDMA_NUM_OPCODE] = {
	[RDMA_OPCODE_RC_SEND_FIRST] = {
		.name = "RDMA_OPCODE_RC_SEND_FIRST",
		.mask = RDMA_PAYLOAD_MASK | RDMA_REQ_MASK | RDMA_RWR_MASK |
			RDMA_SEND_MASK | RDMA_START_MASK,
		.length = RDMA_BTH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_SEND_MIDDLE] = {
		.name = "RDMA_OPCODE_RC_SEND_MIDDLE",
		.mask = RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_SEND_MASK | RDMA_MIDDLE_MASK,
		.length = RDMA_BTH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_SEND_LAST] = {
		.name = "RDMA_OPCODE_RC_SEND_LAST",
		.mask = RDMA_PAYLOAD_MASK | RDMA_REQ_MASK | RDMA_COMP_MASK |
			RDMA_SEND_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_SEND_LAST_WITH_IMMEDIATE] = {
		.name = "RDMA_OPCODE_RC_SEND_LAST_WITH_IMMEDIATE",
		.mask = RDMA_IMMDT_MASK | RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_COMP_MASK | RDMA_SEND_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_IMMDT] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES,
		},
	},
	[RDMA_OPCODE_RC_SEND_ONLY] = {
		.name = "RDMA_OPCODE_RC_SEND_ONLY",
		.mask = RDMA_PAYLOAD_MASK | RDMA_REQ_MASK | RDMA_COMP_MASK |
			RDMA_RWR_MASK | RDMA_SEND_MASK | RDMA_START_MASK |
			RDMA_END_MASK,
		.length = RDMA_BTH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_SEND_ONLY_WITH_IMMEDIATE] = {
		.name = "RDMA_OPCODE_RC_SEND_ONLY_WITH_IMMEDIATE",
		.mask = RDMA_IMMDT_MASK | RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_COMP_MASK | RDMA_RWR_MASK | RDMA_SEND_MASK |
			RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_IMMDT] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES,
		},
	},
	[RDMA_OPCODE_RC_RDMA_WRITE_FIRST] = {
		.name = "RDMA_OPCODE_RC_RDMA_WRITE_FIRST",
		.mask = RDMA_RETH_MASK | RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_WRITE_MASK | RDMA_START_MASK,
		.length = RDMA_BTH_BYTES + RDMA_RETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RETH] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RETH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_RDMA_WRITE_MIDDLE] = {
		.name = "RDMA_OPCODE_RC_RDMA_WRITE_MIDDLE",
		.mask = RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_WRITE_MASK | RDMA_MIDDLE_MASK,
		.length = RDMA_BTH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_RDMA_WRITE_LAST] = {
		.name = "RDMA_OPCODE_RC_RDMA_WRITE_LAST",
		.mask = RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_WRITE_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_RDMA_WRITE_LAST_WITH_IMMEDIATE] = {
		.name = "RDMA_OPCODE_RC_RDMA_WRITE_LAST_WITH_IMMEDIATE",
		.mask = RDMA_IMMDT_MASK | RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_WRITE_MASK | RDMA_COMP_MASK | RDMA_RWR_MASK |
			RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_IMMDT] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES,
		},
	},
	[RDMA_OPCODE_RC_RDMA_WRITE_ONLY] = {
		.name = "RDMA_OPCODE_RC_RDMA_WRITE_ONLY",
		.mask = RDMA_RETH_MASK | RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_WRITE_MASK | RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_RETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RETH] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RETH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_RDMA_WRITE_ONLY_WITH_IMMEDIATE] = {
		.name = "RDMA_OPCODE_RC_RDMA_WRITE_ONLY_WITH_IMMEDIATE",
		.mask = RDMA_RETH_MASK | RDMA_IMMDT_MASK | RDMA_PAYLOAD_MASK |
			RDMA_REQ_MASK | RDMA_WRITE_MASK | RDMA_COMP_MASK |
			RDMA_RWR_MASK | RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES + RDMA_RETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RETH] = RDMA_BTH_BYTES,
			[RDMA_IMMDT] = RDMA_BTH_BYTES + RDMA_RETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RETH_BYTES + RDMA_IMMDT_BYTES,
		},
	},
	[RDMA_OPCODE_RC_RDMA_READ_REQUEST] = {
		.name = "RDMA_OPCODE_RC_RDMA_READ_REQUEST",
		.mask = RDMA_RETH_MASK | RDMA_REQ_MASK | RDMA_READ_MASK |
			RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_RETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RETH] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RETH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_RDMA_READ_RESPONSE_FIRST] = {
		.name = "RDMA_OPCODE_RC_RDMA_READ_RESPONSE_FIRST",
		.mask = RDMA_AETH_MASK | RDMA_PAYLOAD_MASK | RDMA_ACK_MASK |
			RDMA_START_MASK,
		.length = RDMA_BTH_BYTES + RDMA_AETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_AETH] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_AETH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_RDMA_READ_RESPONSE_MIDDLE] = {
		.name = "RDMA_OPCODE_RC_RDMA_READ_RESPONSE_MIDDLE",
		.mask = RDMA_PAYLOAD_MASK | RDMA_ACK_MASK |
			RDMA_MIDDLE_MASK,
		.length = RDMA_BTH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_RDMA_READ_RESPONSE_LAST] = {
		.name = "RDMA_OPCODE_RC_RDMA_READ_RESPONSE_LAST",
		.mask = RDMA_AETH_MASK | RDMA_PAYLOAD_MASK | RDMA_ACK_MASK |
			RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_AETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_AETH] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_AETH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_RDMA_READ_RESPONSE_ONLY] = {
		.name = "RDMA_OPCODE_RC_RDMA_READ_RESPONSE_ONLY",
		.mask = RDMA_AETH_MASK | RDMA_PAYLOAD_MASK | RDMA_ACK_MASK |
			RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_AETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_AETH] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_AETH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_ACKNOWLEDGE] = {
		.name = "RDMA_OPCODE_RC_ACKNOWLEDGE",
		.mask = RDMA_AETH_MASK | RDMA_ACK_MASK | RDMA_START_MASK |
			RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_AETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_AETH] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_AETH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_ATOMIC_ACKNOWLEDGE] = {
		.name = "RDMA_OPCODE_RC_ATOMIC_ACKNOWLEDGE",
		.mask = RDMA_AETH_MASK | RDMA_ATMACK_MASK | RDMA_ACK_MASK |
			RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_ATMACK_BYTES + RDMA_AETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_AETH] = RDMA_BTH_BYTES,
			[RDMA_ATMACK] = RDMA_BTH_BYTES + RDMA_AETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_ATMACK_BYTES + RDMA_AETH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_COMPARE_SWAP] = {
		.name = "RDMA_OPCODE_RC_COMPARE_SWAP",
		.mask = RDMA_ATMETH_MASK | RDMA_REQ_MASK | RDMA_ATOMIC_MASK |
			RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_ATMETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_ATMETH] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_ATMETH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_FETCH_ADD] = {
		.name = "RDMA_OPCODE_RC_FETCH_ADD",
		.mask = RDMA_ATMETH_MASK | RDMA_REQ_MASK | RDMA_ATOMIC_MASK |
			RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_ATMETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_ATMETH] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_ATMETH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_SEND_LAST_WITH_INVALIDATE] = {
		.name = "RDMA_OPCODE_RC_SEND_LAST_WITH_INVALIDATE",
		.mask = RDMA_IETH_MASK | RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_COMP_MASK | RDMA_SEND_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_IETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_IETH] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_IETH_BYTES,
		},
	},
	[RDMA_OPCODE_RC_SEND_ONLY_WITH_INVALIDATE] = {
		.name = "RDMA_OPCODE_RC_SEND_ONLY_INV",
		.mask = RDMA_IETH_MASK | RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_COMP_MASK | RDMA_RWR_MASK | RDMA_SEND_MASK |
			RDMA_END_MASK | RDMA_START_MASK,
		.length = RDMA_BTH_BYTES + RDMA_IETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_IETH] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_IETH_BYTES,
		},
	},

	/* UC */
	[RDMA_OPCODE_UC_SEND_FIRST] = {
		.name = "RDMA_OPCODE_UC_SEND_FIRST",
		.mask = RDMA_PAYLOAD_MASK | RDMA_REQ_MASK | RDMA_RWR_MASK |
			RDMA_SEND_MASK | RDMA_START_MASK,
		.length = RDMA_BTH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES,
		},
	},
	[RDMA_OPCODE_UC_SEND_MIDDLE] = {
		.name = "RDMA_OPCODE_UC_SEND_MIDDLE",
		.mask = RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_SEND_MASK | RDMA_MIDDLE_MASK,
		.length = RDMA_BTH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES,
		},
	},
	[RDMA_OPCODE_UC_SEND_LAST] = {
		.name = "RDMA_OPCODE_UC_SEND_LAST",
		.mask = RDMA_PAYLOAD_MASK | RDMA_REQ_MASK | RDMA_COMP_MASK |
			RDMA_SEND_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES,
		},
	},
	[RDMA_OPCODE_UC_SEND_LAST_WITH_IMMEDIATE] = {
		.name = "RDMA_OPCODE_UC_SEND_LAST_WITH_IMMEDIATE",
		.mask = RDMA_IMMDT_MASK | RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_COMP_MASK | RDMA_SEND_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_IMMDT] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES,
		},
	},
	[RDMA_OPCODE_UC_SEND_ONLY] = {
		.name = "RDMA_OPCODE_UC_SEND_ONLY",
		.mask = RDMA_PAYLOAD_MASK | RDMA_REQ_MASK | RDMA_COMP_MASK |
			RDMA_RWR_MASK | RDMA_SEND_MASK | RDMA_START_MASK |
			RDMA_END_MASK,
		.length = RDMA_BTH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES,
		},
	},
	[RDMA_OPCODE_UC_SEND_ONLY_WITH_IMMEDIATE] = {
		.name = "RDMA_OPCODE_UC_SEND_ONLY_WITH_IMMEDIATE",
		.mask = RDMA_IMMDT_MASK | RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_COMP_MASK | RDMA_RWR_MASK | RDMA_SEND_MASK |
			RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_IMMDT] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES,
		},
	},
	[RDMA_OPCODE_UC_RDMA_WRITE_FIRST] = {
		.name = "RDMA_OPCODE_UC_RDMA_WRITE_FIRST",
		.mask = RDMA_RETH_MASK | RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_WRITE_MASK | RDMA_START_MASK,
		.length = RDMA_BTH_BYTES + RDMA_RETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RETH] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RETH_BYTES,
		},
	},
	[RDMA_OPCODE_UC_RDMA_WRITE_MIDDLE] = {
		.name = "RDMA_OPCODE_UC_RDMA_WRITE_MIDDLE",
		.mask = RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_WRITE_MASK | RDMA_MIDDLE_MASK,
		.length = RDMA_BTH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES,
		},
	},
	[RDMA_OPCODE_UC_RDMA_WRITE_LAST] = {
		.name = "RDMA_OPCODE_UC_RDMA_WRITE_LAST",
		.mask = RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_WRITE_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES,
		},
	},
	[RDMA_OPCODE_UC_RDMA_WRITE_LAST_WITH_IMMEDIATE] = {
		.name = "RDMA_OPCODE_UC_RDMA_WRITE_LAST_WITH_IMMEDIATE",
		.mask = RDMA_IMMDT_MASK | RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_WRITE_MASK | RDMA_COMP_MASK | RDMA_RWR_MASK |
			RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_IMMDT] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES,
		},
	},
	[RDMA_OPCODE_UC_RDMA_WRITE_ONLY] = {
		.name = "RDMA_OPCODE_UC_RDMA_WRITE_ONLY",
		.mask = RDMA_RETH_MASK | RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_WRITE_MASK | RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_RETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RETH] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RETH_BYTES,
		},
	},
	[RDMA_OPCODE_UC_RDMA_WRITE_ONLY_WITH_IMMEDIATE] = {
		.name = "RDMA_OPCODE_UC_RDMA_WRITE_ONLY_WITH_IMMEDIATE",
		.mask = RDMA_RETH_MASK | RDMA_IMMDT_MASK | RDMA_PAYLOAD_MASK |
			RDMA_REQ_MASK | RDMA_WRITE_MASK | RDMA_COMP_MASK |
			RDMA_RWR_MASK | RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES + RDMA_RETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RETH] = RDMA_BTH_BYTES,
			[RDMA_IMMDT] = RDMA_BTH_BYTES + RDMA_RETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RETH_BYTES + RDMA_IMMDT_BYTES,
		},
	},

	/* RD */
	[RDMA_OPCODE_RD_SEND_FIRST] = {
		.name = "RDMA_OPCODE_RD_SEND_FIRST",
		.mask = RDMA_RDETH_MASK | RDMA_DETH_MASK | RDMA_PAYLOAD_MASK |
			RDMA_REQ_MASK | RDMA_RWR_MASK | RDMA_SEND_MASK |
			RDMA_START_MASK,
		.length = RDMA_BTH_BYTES + RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_DETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES + RDMA_DETH_BYTES,
		},
	},
	[RDMA_OPCODE_RD_SEND_MIDDLE] = {
		.name = "RDMA_OPCODE_RD_SEND_MIDDLE",
		.mask = RDMA_RDETH_MASK | RDMA_DETH_MASK | RDMA_PAYLOAD_MASK |
			RDMA_REQ_MASK | RDMA_SEND_MASK | RDMA_MIDDLE_MASK,
		.length = RDMA_BTH_BYTES + RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_DETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES + RDMA_DETH_BYTES,
		},
	},
	[RDMA_OPCODE_RD_SEND_LAST] = {
		.name = "RDMA_OPCODE_RD_SEND_LAST",
		.mask = RDMA_RDETH_MASK | RDMA_DETH_MASK | RDMA_PAYLOAD_MASK |
			RDMA_REQ_MASK | RDMA_COMP_MASK | RDMA_SEND_MASK |
			RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_DETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES + RDMA_DETH_BYTES,
		},
	},
	[RDMA_OPCODE_RD_SEND_LAST_WITH_IMMEDIATE] = {
		.name = "RDMA_OPCODE_RD_SEND_LAST_WITH_IMMEDIATE",
		.mask = RDMA_RDETH_MASK | RDMA_DETH_MASK | RDMA_IMMDT_MASK |
			RDMA_PAYLOAD_MASK | RDMA_REQ_MASK | RDMA_COMP_MASK |
			RDMA_SEND_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES +
			  RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_DETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_IMMDT] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES +
				RDMA_DETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES +
				RDMA_DETH_BYTES + RDMA_IMMDT_BYTES,
		},
	},
	[RDMA_OPCODE_RD_SEND_ONLY] = {
		.name = "RDMA_OPCODE_RD_SEND_ONLY",
		.mask = RDMA_RDETH_MASK | RDMA_DETH_MASK | RDMA_PAYLOAD_MASK |
			RDMA_REQ_MASK | RDMA_COMP_MASK | RDMA_RWR_MASK |
			RDMA_SEND_MASK | RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_DETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES + RDMA_DETH_BYTES,
		},
	},
	[RDMA_OPCODE_RD_SEND_ONLY_WITH_IMMEDIATE] = {
		.name = "RDMA_OPCODE_RD_SEND_ONLY_WITH_IMMEDIATE",
		.mask = RDMA_RDETH_MASK | RDMA_DETH_MASK | RDMA_IMMDT_MASK |
			RDMA_PAYLOAD_MASK | RDMA_REQ_MASK | RDMA_COMP_MASK |
			RDMA_RWR_MASK | RDMA_SEND_MASK | RDMA_START_MASK |
			RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES + RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_DETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_IMMDT] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES + RDMA_DETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES +
				RDMA_DETH_BYTES + RDMA_IMMDT_BYTES,
		},
	},
	[RDMA_OPCODE_RD_RDMA_WRITE_FIRST] = {
		.name = "RDMA_OPCODE_RD_RDMA_WRITE_FIRST",
		.mask = RDMA_RDETH_MASK | RDMA_DETH_MASK | RDMA_RETH_MASK |
			RDMA_PAYLOAD_MASK | RDMA_REQ_MASK | RDMA_WRITE_MASK |
			RDMA_START_MASK,
		.length = RDMA_BTH_BYTES + RDMA_RETH_BYTES +
			  RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_DETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_RETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES +
				RDMA_DETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES +
				RDMA_DETH_BYTES + RDMA_RETH_BYTES,
		},
	},
	[RDMA_OPCODE_RD_RDMA_WRITE_MIDDLE] = {
		.name = "RDMA_OPCODE_RD_RDMA_WRITE_MIDDLE",
		.mask = RDMA_RDETH_MASK | RDMA_DETH_MASK | RDMA_PAYLOAD_MASK |
			RDMA_REQ_MASK | RDMA_WRITE_MASK | RDMA_MIDDLE_MASK,
		.length = RDMA_BTH_BYTES + RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_DETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES + RDMA_DETH_BYTES,
		},
	},
	[RDMA_OPCODE_RD_RDMA_WRITE_LAST] = {
		.name = "RDMA_OPCODE_RD_RDMA_WRITE_LAST",
		.mask = RDMA_RDETH_MASK | RDMA_DETH_MASK | RDMA_PAYLOAD_MASK |
			RDMA_REQ_MASK | RDMA_WRITE_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_DETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES + RDMA_DETH_BYTES,
		},
	},
	[RDMA_OPCODE_RD_RDMA_WRITE_LAST_WITH_IMMEDIATE] = {
		.name = "RDMA_OPCODE_RD_RDMA_WRITE_LAST_WITH_IMMEDIATE",
		.mask = RDMA_RDETH_MASK | RDMA_DETH_MASK | RDMA_IMMDT_MASK |
			RDMA_PAYLOAD_MASK | RDMA_REQ_MASK | RDMA_WRITE_MASK |
			RDMA_COMP_MASK | RDMA_RWR_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES + RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_DETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_IMMDT] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES + RDMA_DETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES +
				RDMA_DETH_BYTES + RDMA_IMMDT_BYTES,
		},
	},
	[RDMA_OPCODE_RD_RDMA_WRITE_ONLY] = {
		.name = "RDMA_OPCODE_RD_RDMA_WRITE_ONLY",
		.mask = RDMA_RDETH_MASK | RDMA_DETH_MASK | RDMA_RETH_MASK |
			RDMA_PAYLOAD_MASK | RDMA_REQ_MASK | RDMA_WRITE_MASK |
			RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_RETH_BYTES + RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_DETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_RETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES + RDMA_DETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES +
				RDMA_DETH_BYTES + RDMA_RETH_BYTES,
		},
	},
	[RDMA_OPCODE_RD_RDMA_WRITE_ONLY_WITH_IMMEDIATE] = {
		.name = "RDMA_OPCODE_RD_RDMA_WRITE_ONLY_WITH_IMMEDIATE",
		.mask = RDMA_RDETH_MASK | RDMA_DETH_MASK | RDMA_RETH_MASK |
			RDMA_IMMDT_MASK | RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_WRITE_MASK | RDMA_COMP_MASK | RDMA_RWR_MASK |
			RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES + RDMA_RETH_BYTES +
			  RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_DETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_RETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES +
				RDMA_DETH_BYTES,
			[RDMA_IMMDT] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES +
				RDMA_DETH_BYTES + RDMA_RETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES +
				RDMA_DETH_BYTES + RDMA_RETH_BYTES + RDMA_IMMDT_BYTES,
		},
	},
	[RDMA_OPCODE_RD_RDMA_READ_REQUEST] = {
		.name = "RDMA_OPCODE_RD_RDMA_READ_REQUEST",
		.mask = RDMA_RDETH_MASK | RDMA_DETH_MASK | RDMA_RETH_MASK |
			RDMA_REQ_MASK | RDMA_READ_MASK | RDMA_START_MASK |
			RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_RETH_BYTES +
			  RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_DETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_RETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES +
				RDMA_DETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RETH_BYTES +
				RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		},
	},
	[RDMA_OPCODE_RD_RDMA_READ_RESPONSE_FIRST] = {
		.name = "RDMA_OPCODE_RD_RDMA_READ_RESPONSE_FIRST",
		.mask = RDMA_RDETH_MASK | RDMA_AETH_MASK | RDMA_PAYLOAD_MASK |
			RDMA_ACK_MASK | RDMA_START_MASK,
		.length = RDMA_BTH_BYTES + RDMA_AETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_AETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES + RDMA_AETH_BYTES,
		},
	},
	[RDMA_OPCODE_RD_RDMA_READ_RESPONSE_MIDDLE] = {
		.name = "RDMA_OPCODE_RD_RDMA_READ_RESPONSE_MIDDLE",
		.mask = RDMA_RDETH_MASK | RDMA_PAYLOAD_MASK | RDMA_ACK_MASK |
			RDMA_MIDDLE_MASK,
		.length = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
		},
	},
	[RDMA_OPCODE_RD_RDMA_READ_RESPONSE_LAST] = {
		.name = "RDMA_OPCODE_RD_RDMA_READ_RESPONSE_LAST",
		.mask = RDMA_RDETH_MASK | RDMA_AETH_MASK | RDMA_PAYLOAD_MASK |
			RDMA_ACK_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_AETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_AETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES + RDMA_AETH_BYTES,
		},
	},
	[RDMA_OPCODE_RD_RDMA_READ_RESPONSE_ONLY] = {
		.name = "RDMA_OPCODE_RD_RDMA_READ_RESPONSE_ONLY",
		.mask = RDMA_RDETH_MASK | RDMA_AETH_MASK | RDMA_PAYLOAD_MASK |
			RDMA_ACK_MASK | RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_AETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_AETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES + RDMA_AETH_BYTES,
		},
	},
	[RDMA_OPCODE_RD_ACKNOWLEDGE] = {
		.name = "RDMA_OPCODE_RD_ACKNOWLEDGE",
		.mask = RDMA_RDETH_MASK | RDMA_AETH_MASK | RDMA_ACK_MASK |
			RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_AETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_AETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
		},
	},
	[RDMA_OPCODE_RD_ATOMIC_ACKNOWLEDGE] = {
		.name = "RDMA_OPCODE_RD_ATOMIC_ACKNOWLEDGE",
		.mask = RDMA_RDETH_MASK | RDMA_AETH_MASK | RDMA_ATMACK_MASK |
			RDMA_ACK_MASK | RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_ATMACK_BYTES + RDMA_AETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_AETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_ATMACK] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES + RDMA_AETH_BYTES,
		},
	},
	[RDMA_OPCODE_RD_COMPARE_SWAP] = {
		.name = "RD_COMPARE_SWAP",
		.mask = RDMA_RDETH_MASK | RDMA_DETH_MASK | RDMA_ATMETH_MASK |
			RDMA_REQ_MASK | RDMA_ATOMIC_MASK | RDMA_START_MASK |
			RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_ATMETH_BYTES +
			  RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_DETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_ATMETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES +
				RDMA_DETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_ATMETH_BYTES +
				RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		},
	},
	[RDMA_OPCODE_RD_FETCH_ADD] = {
		.name = "RDMA_OPCODE_RD_FETCH_ADD",
		.mask = RDMA_RDETH_MASK | RDMA_DETH_MASK | RDMA_ATMETH_MASK |
			RDMA_REQ_MASK | RDMA_ATOMIC_MASK | RDMA_START_MASK |
			RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_ATMETH_BYTES +
			  RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_RDETH] = RDMA_BTH_BYTES,
			[RDMA_DETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES,
			[RDMA_ATMETH] = RDMA_BTH_BYTES + RDMA_RDETH_BYTES +
				RDMA_DETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_ATMETH_BYTES +
				RDMA_DETH_BYTES + RDMA_RDETH_BYTES,
		},
	},

	/* UD */
	[RDMA_OPCODE_UD_SEND_ONLY] = {
		.name = "RDMA_OPCODE_UD_SEND_ONLY",
		.mask = RDMA_DETH_MASK | RDMA_PAYLOAD_MASK | RDMA_REQ_MASK |
			RDMA_COMP_MASK | RDMA_RWR_MASK | RDMA_SEND_MASK |
			RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_DETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_DETH] = RDMA_BTH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_DETH_BYTES,
		},
	},
	[RDMA_OPCODE_UD_SEND_ONLY_WITH_IMMEDIATE] = {
		.name = "RDMA_OPCODE_UD_SEND_ONLY_WITH_IMMEDIATE",
		.mask = RDMA_DETH_MASK | RDMA_IMMDT_MASK | RDMA_PAYLOAD_MASK |
			RDMA_REQ_MASK | RDMA_COMP_MASK | RDMA_RWR_MASK |
			RDMA_SEND_MASK | RDMA_START_MASK | RDMA_END_MASK,
		.length = RDMA_BTH_BYTES + RDMA_IMMDT_BYTES + RDMA_DETH_BYTES,
		.offset = {
			[RDMA_BTH] = 0,
			[RDMA_DETH] = RDMA_BTH_BYTES,
			[RDMA_IMMDT] = RDMA_BTH_BYTES + RDMA_DETH_BYTES,
			[RDMA_PAYLOAD] = RDMA_BTH_BYTES + RDMA_DETH_BYTES + RDMA_IMMDT_BYTES,
		},
	},
};
