/* SPDX-License-Identifier: Marvell-MIT
 * Copyright (c) 2025 Marvell.
 */
#ifndef RDMA_DEV_CAP_PRIV_H
#define RDMA_DEV_CAP_PRIV_H

#include <dao_log.h>
#include <rte_byteorder.h>

#define DEFAULT_MAX_VALUE (1 << 20)

enum rdma_device_cap_flags {
	RDMA_DEVICE_RESIZE_MAX_WR = 1 << 0,
	RDMA_DEVICE_BAD_PKEY_CNTR = 1 << 1,
	RDMA_DEVICE_BAD_QKEY_CNTR = 1 << 2,
	RDMA_DEVICE_RAW_MULTI = 1 << 3,
	RDMA_DEVICE_AUTO_PATH_MIG = 1 << 4,
	RDMA_DEVICE_CHANGE_PHY_PORT = 1 << 5,
	RDMA_DEVICE_UD_AV_PORT_ENFORCE = 1 << 6,
	RDMA_DEVICE_CURR_QP_STATE_MOD = 1 << 7,
	RDMA_DEVICE_SHUTDOWN_PORT = 1 << 8,
	RDMA_DEVICE_INIT_TYPE = 1 << 9,
	RDMA_DEVICE_PORT_ACTIVE_EVENT = 1 << 10,
	RDMA_DEVICE_SYS_IMAGE_GUID = 1 << 11,
	RDMA_DEVICE_RC_RNR_NAK_GEN = 1 << 12,
	RDMA_DEVICE_SRQ_RESIZE = 1 << 13,
	RDMA_DEVICE_N_NOTIFY_CQE = 1 << 14,
	RDMA_DEVICE_XRC = 1 << 20,
};

/* default/initial octep_rdma device parameter settings */
enum rdma_device_param {
	RDMA_MAX_MR_SIZE = -1ull,
	RDMA_PAGE_SIZE_CAP = 0xfffff000,
	RDMA_MAX_QP_WR = 1024,
	RDMA_DEVICE_CAP_FLAGS = RDMA_DEVICE_RC_RNR_NAK_GEN,
	RDMA_MAX_SGE = 32,
	RDMA_MAX_SGE_RD = 32,
	RDMA_MAX_CQ = 1024,
	RDMA_MAX_LOG_CQE = 24,
	RDMA_MAX_PD = 1024,
	RDMA_MAX_QP_RD_ATOM = 2,
	RDMA_MAX_RES_RD_ATOM = 2,
	RDMA_MAX_QP_INIT_RD_ATOM = 2,
	RDMA_MAX_MCAST_GRP = 8192,
	RDMA_MAX_MCAST_QP_ATTACH = 56,
	RDMA_MAX_TOT_MCAST_QP_ATTACH = 0x70000,
	RDMA_MAX_AH = 1024,
	RDMA_MIN_AH_INDEX = 1,
	RDMA_MAX_AH_INDEX = RDMA_MAX_AH,
	RDMA_MAX_SRQ_WR = 1024,
	RDMA_MIN_SRQ_WR = 1,
	RDMA_MAX_SRQ_SGE = 27,
	RDMA_MIN_SRQ_SGE = 1,
	RDMA_MAX_FMR_PAGE_LIST_LEN = 512,
	RDMA_MAX_PKEYS = 64,
	RDMA_LOCAL_CA_ACK_DELAY = 15,

	RDMA_MAX_UCONTEXT = 1024,

	RDMA_NUM_PORT = 1,

	RDMA_MIN_QP_INDEX = 16,
	RDMA_MAX_QP_INDEX = 1024,
	RDMA_MAX_QP = RDMA_MAX_QP_INDEX - RDMA_MIN_QP_INDEX,

	RDMA_MIN_SRQ_INDEX = 1,
	RDMA_MAX_SRQ_INDEX = 1024,
	RDMA_MAX_SRQ = RDMA_MAX_SRQ_INDEX - RDMA_MIN_SRQ_INDEX,

	RDMA_MAX_MR = 1024,

	RDMA_MAX_PKT_PER_ACK = 32,

	RDMA_MAX_UNACKED_PSNS = 32,

	/* Max inflight SKBs per queue pair */
	RDMA_INFLIGHT_SKBS_PER_QP_HIGH = 64,
	RDMA_INFLIGHT_SKBS_PER_QP_LOW = 16,

	/* Max number of iterations of each work item
	 * before yielding the cpu to let other
	 * work make progress
	 */
	RDMA_MAX_ITERATIONS = 1024,

	/* Delay before calling arbiter timer */
	RDMA_NSEC_ARB_TIMER_DELAY = 200,

	/* IBTA v1.4 A3.3.1 VENDOR INFORMATION section */
	RDMA_VENDOR_ID = 0XFFFFFF,
	RDMA_MAX_MSG_SZ = 0xFFFFFFFF,
};

/* default/initial octep_rdma port parameters */
enum rdma_port_param {
	RDMA_PORT_GID_TBL_LEN = 1024,
	RDMA_PORT_PORT_CAP_FLAGS = 0,
	/* Max 16k */
	RDMA_PORT_MAX_MSG_SZ = 0x800000,
	RDMA_PORT_BAD_PKEY_CNTR = 0,
	RDMA_PORT_QKEY_VIOL_CNTR = 0,
	RDMA_PORT_LID = 0,
	RDMA_PORT_SM_LID = 0,
	RDMA_PORT_SM_SL = 0,
	RDMA_PORT_LMC = 0,
	RDMA_PORT_MAX_VL_NUM = 1,
	RDMA_PORT_SUBNET_TIMEOUT = 0,
	RDMA_PORT_INIT_TYPE_REPLY = 0,
	RDMA_PORT_ACTIVE_WIDTH = 1,
	RDMA_PORT_ACTIVE_SPEED = 1,
	RDMA_PORT_PKEY_TBL_LEN = 1,
	RDMA_PORT_PHYS_STATE = 2, /* POLLING */
	RDMA_PORT_SUBNET_PREFIX = 0xfe80000000000000ULL,
};

int rdma_query_device_cap(int port, void *cap);
int rdma_query_port_attr(int port, void *attr);

#endif /* RDMA_DEV_CAP_PRIV_H */
