/* SPDX-License-Identifier: Marvell-MIT
 * Copyright (c) 2026 Marvell.
 */

#ifndef __LC_TEST_COMP_PRIV_H__
#define __LC_TEST_COMP_PRIV_H__

static const char large_text[] = {
	"The quick brown fox jumps over the lazy dog while the silent wind moves across "
	"the valley and distant hills shimmer under the afternoon sun. Compression testing "
	"often requires moderately random text with some repeated phrases so that algorithms "
	"such as gzip, lz4, zstd, or hardware compression devices can demonstrate their "
	"effectiveness in identifying patterns and reducing redundancy within data streams. "
	"In many networking and storage workloads, data rarely appears as perfectly random "
	"bytes. Instead it contains fragments of structured language, logs, identifiers, "
	"timestamps, and repeated keywords. For example a system log might repeatedly contain "
	"phrases such as connection established, connection closed, packet received, packet "
	"transmitted, checksum verified, or buffer allocation completed. These repeated patterns "
	"give compression algorithms the opportunity to build dictionaries and encode repeated "
	"sequences efficiently. Consider a scenario where multiple services generate diagnostic "
	"logs simultaneously. Sometimes numeric sequences are inserted as well: 1029384756 "
	"5647382910 9182736455 11223344556677889900. Each service reports initialization events, "
	"configuration values, and operational status. Messages such as service started "
	"successfully, initializing worker threads, allocating packet buffers, enabling "
	"compression engine, and waiting for incoming requests may appear frequently across logs."
	" When such logs are compressed, algorithms can exploit repeated substrings across the "
	"dataset to significantly reduce storage requirements. Random looking segments may also "
	"appear in the data. Unique identifiers like f9a3d2c1b8e74a21 or transaction tokens such "
	"as a8b7c6d5e4f31209 introduce entropy that prevents perfect compression. Sometimes "
	"numeric sequences are inserted as well: 1029384756 5647382910 9182736455 "
	"11223344556677889900. Network traces may include hexadecimal payload dumps like "
	"7F3A9C01D4B8E211FFAA1099CC22DD44 which resemble random bytes but often contain recurring "
	"headers or protocol fields. In packet processing systems built with high performance "
	"frameworks, data buffers may contain protocol headers, metadata, and payload fragments "
	"chained together through buffer segments. Sometimes numeric sequences are inserted as "
	"well: 1029384756 5647382910 9182736455 11223344556677889900. The payload itself might "
	"contain application data such as JSON messages, telemetry streams, or text fragments "
	"similar to this paragraph. When evaluating compression hardware or software "
	"implementations, developers often feed sample data that mimics real world "
	"characteristics rather than completely random noise. A practical compression test dataset"
	" therefore combines structured language, repeated phrases, identifiers, and occasional "
	"pseudo random sequences. Sometimes numeric sequences are inserted as well: 1029384756 "
	"5647382910 9182736455 11223344556677889900. For instance repeated markers like "
	"BEGIN_BLOCK and END_BLOCK may appear several times. BEGIN_BLOCK This section represents"
	" a repeated marker that helps compression algorithms detect patterns. END_BLOCK Later "
	"another marker might appear again. BEGIN_BLOCK This section represents a repeated marker"
	" that helps compression algorithms detect patterns. END_BLOCK Additional filler text can"
	" simulate larger payloads. Engineers may repeat descriptive sentences about buffer "
	"management, memory allocation, queue operations, and device drivers. Example phrases "
	"include allocating mbuf segments, chaining packet buffers, enqueueing operations to the "
	"compression device, dequeueing completed operations, validating output length, and "
	"updating packet metadata fields. Sometimes numeric sequences are inserted as well: "
	"1029384756 5647382910 9182736455 11223344556677889900. These sequences look random but "
	"still contain digits that compression algorithms may partially encode For further "
	"diversity, here are a few mixed tokens: alpha_beta_gamma delta_theta_lambda "
	"network_packet_stream compression_pipeline hardware_accelerator buffer_descriptor "
	"queue_index ring_pointer memory_region flow_identifier packet_sequence. Finally the "
	"dataset concludes with a simple repeating phrase used to help compression ratio "
	"measurement. Data compression test payload segment repeated for evaluation. Data "
	"compression test payload segment repeated for evaluation. Data compression test payload "
	"segment repeated for evaluation. Data compression test payload segment repeated for "
	"evaluation. Data compression test payload segment repeated for evaluation. End of sample"
	" payload used for compression benchmarking and validation in networking and systems "
	"software environments. Sometimes numeric sequences are inserted as well: 1029384756 "
	"5647382910 9182736455 11223344556677889900."};

#endif /* __LC_TEST_COMP_PRIV_H__ */
