/* SPDX-License-Identifier: Marvell-MIT
 * Copyright(C) 2025 Marvell.
 */

syntax = "proto3";

package dao_card_manager;

service DaoCardService {
	rpc Init(CardConfig) returns (CardResponse) {}
	rpc Fini(Emp) returns (Emp){}
	rpc Info(Emp) returns (CardInfo) {}
	rpc Stats(Emp) returns (CardStats) {}
	rpc AppFallback(Emp) returns (CardResponse) {}
	rpc FileUpdate(FileUpdateReq) returns (CardResponse) {}
	rpc Dmesg(Emp) returns (DmesgLogs) {}
}

enum FileTransferType {
	APP_UPDATE = 0;
	FW_UPDATE = 1;
	FAILSAFE_UPDATE = 2;
}

enum BootSource {
	BOOT_SOURCE_UNSUPPORTED = 0;      // crypto-agent does not support boot source detection
	BOOT_SOURCE_SCRIPT_FAILURE = 2;   // script missing or failed execution
	BOOT_SOURCE_MMC = 11;             // determined main (MMC)
	BOOT_SOURCE_SPI = 12;             // determined failsafe (SPI)
}

message CardConfig {
	uint32 argc = 1;
	repeated string argv = 2;
	uint32 crypto_nb_desc = 3;
}

message CardInfo {
	string version = 1;
	uint32 nb_devs = 2;
	uint32 max_sessions = 3;
	BootSource boot_source = 4;
}

message CardResponse {
	int32 err = 1;
}

message FileUpdateReq {
	string file_name = 1;
	bytes file_content = 2;
	bool is_last_chunk = 3;
	string checksum = 4;
	FileTransferType transfer_type = 5;
}

message CardStats {
	repeated uint64 rx_packets = 1;
	repeated uint64 tx_packets = 2;
}

message DmesgLogs {
	string text = 1; // Truncated dmesg output if exceeds server limit
}

message Emp {
}
