name: DAO-Sync

on:
  pull_request:
    types: [closed]
    branches:
      - dao-devel
      - dao-24.05
      - dao-24.09
      - dao-25.05
      - dao-25.10
      - dao-lc-26.01

jobs:
  sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push merged branch to target repo
        env:
          TOKEN: ${{ secrets.TOKEN_GITHUB_SYNC }}
          BRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          set -euo pipefail
          git checkout "$BRANCH"
          git pull origin "$BRANCH"

          git push \
            https://x-access-token:${TOKEN}@github.com/MarvellEmbeddedProcessors/dao.git \
            HEAD:"$BRANCH"
